config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"

  resources :entities
  resources :groups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user, foreign_key: 'author_id'
  validates :name, presence: true
  validates :amount, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :entities, dependent: :destroy
  validates :name, presence: true
  validates :icon, presence: true
  mount_uploader :icon, IconUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: false
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show destroy]
  before_action :authenticate_user!

  def index
    @entities = Entity.all
  end

  def show
    # show
  end

  def new
    @groups = Group.all # Fetch the groups you want to display in the new entity form.
    @entity = Entity.new
    @entity.group_id = params[:group_id] # Set the group_id based on your requirements.
  end

  def create
    puts params
    puts '-------------------------------'

    @entity = Entity.new(entity_params)
    @entity.author_id = current_user.id
    if @entity.save
      redirect_to entities_path(@entity.group_id), notice: 'Add new transaction'
    else
      render :new
    end
  end

  def destroy
    @entity = Entity.find(params[:id])
    @entity.destroy
    redirect_to entities_path, notice: 'Transaction was successfully deleted.'
  end

  private

  def set_entity
    @entity = Entity.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(:name, :group_id, :amount)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @groups = Group.all # or any logic to load other groups if needed
  end

  def new
    @group = Group.new
    @groups = Group.all # Load groups to display in the new view.
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    if @group.save
      redirect_to group_path(@group), notice: 'Group was successfully created.'
    else
      render :new
    end
  end

  def edit
    # Render the edit form for the group.
  end

  def update
    if @group.update(group_params)
      redirect_to group_path(@group), notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, notice: 'Group was successfully deleted.'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @groups = Group.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/new.html.erb
<%= form_with model: @entity, url: entities_path, class: "form" do |f| %>
   
  <nav class="navbar navbar-default navbar-expand-lg fixed-top">
    <div class="container flex justify-content0-between align-items-center">

      <div></div>
     
      <h6 class="title">ADD TRANSACTION</h6>

       <%= f.submit "Submit" %>

    </div>
  </nav>

      <div class="d-flex justify-content-start align-items-center bg-white mav-header">

        <%= link_to :back do  %> 
          <i class="fa-solid fa-chevron-left icon" ></i>
        <% end %>

  
    </div>
 
<section class="auth m-3 shadow-sm">

<% if @entity.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this model from being saved:</h2>
    <ul>
      <% @entity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

   <%= f.hidden_field :group_id, autofocus: true, autocomplete: "group_id" , placeholder: "Name" %>

  <div class="field">
    <%= f.text_field :name, autofocus: true, autocomplete: "name" , placeholder: "Name" %>
  </div>

  <div class="field">
    <%= f.number_field :amount, autofocus: true, autocomplete: "amount", placeholder: "Amount" %>
  </div>
</section>
<% end %>

app/views/groups/new.html.erb
<%= form_with model: @group, url: groups_path, class: "form" do |f| %>
   
  <nav class="navbar navbar-default navbar-expand-lg fixed-top">
    <div class="container flex justify-content0-between align-items-center">

      <div></div>
     
      <h6 class="title">ADD CATGEORY</h6>

       <%= f.submit "Submit" %>

    </div>
  </nav>

      <div class=" justify-content-start align-items-center bg-white mav-header">

        <%= link_to root_path do  %> 
          <i class="fa-solid fa-chevron-left icon" ></i>
        <% end %>

  
    </div>
 
<section class="auth m-3 shadow-sm">

<% if @group.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@group.errors.count, "error") %> prohibited this model from being saved:</h2>
    <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div class="field">
    <%= f.text_field :name, autofocus: true, autocomplete: "name" , placeholder: "Name" %>
    
  </div>

  <div class="field">
    <%= f.file_field :icon, autofocus: true, autocomplete: "icon", placeholder: "Icon" %>
  </div>
</section>
<% end %>

app/views/groups/show.html.erb
    <nav class="navbar navbar-default navbar-expand-lg fixed-top">
    <div class="container flex justify-content0-between align-items-center">

      <span></span>
     
        <h6 class="title"><%= @group.name.upcase %></h6>


      <div></div>


    </div>
  </nav>

<div class=" justify-content-between align-items-center bg-white p-2">


    

        <div class=" justify-content-start align-items-center gap-3">
        <%= link_to root_path do  %> 
          <i class="fa-solid fa-chevron-left icon" ></i>
        <% end %>
              <img src="<%= @group.icon %>" height="50" width="50" class="rounded-circle">
              <div class="flex-column d-flex justify-content-between mt-4">
                <%# <h6 class="pb-3 text-black-60"><%= @group.name.capitalize %></h6>
              </div>
            </div>

        <p>$<%= @group.entities.sum(:amount) %></p>
</div>

<div class="mb-5">
<% if @group.entities.empty? %>

    <div class=" flex-column justify-content-center align-items-center m-5">

        <p>Transaction is empty.</p>
        <%= link_to 'Add Transaction', new_entity_path(group_id: @group.id), class: 'btn btn-primary', style: 'background-color: #5fb523;' %>

     </div>
<% else %>




 <% @group.entities.order(created_at: :desc).each do |group|%>


          <div class=" justify-content-between align-items-center bg-white p-2 gap-6 m-2 shadow-sm" >


            <div class=" justify-content-start align-items-center gap-3">

              <div class="flex-column d-flex justify-content-between mt-4">
                <h6 class="pb-3 text-black-60"><%= group.name %></h6>
                <%# <p class="text-black-50"><%= group.created_at.strftime("%Y-%m-%d") %></p>
              </div>
            </div>
            <div class="fw-bold">$<%= group.amount %></div>
        </div>

    <% end %>
<% end %>

</div>
  <div class="position-fixed bottom-0 w-100">
    <div class=" justify-content-center align-items-center bg-white p-2">

  <%= link_to 'Add Transaction', new_entity_path(group_id: @group.id), class: 'btn btn-primary w-100', style: 'background-color: #5fb523;' %>
</div>
</div>

app/views/home/index.html.erb
<nav class="navbar navbar-default navbar-expand-lg fixed-top" style="background-color: #3778c2;">
  <div class="container flex justify-content-between align-items-center">
    <span></span>
    <h6 class="title">CATEGORIES</h6>
    <div></div>
  </div>
</nav>

<div class="d-flex justify-content-between align-items-center bg-white p-2" >

  <h6 class="pt-2">Categories</h6>

  <%= link_to 'Add Category', new_group_path, class: 'btn btn-primary' %>
</div>

<div class="mb-5">

  <% if false %>
    <div class="d-flex flex-column justify-content-center align-items-center m-5">
      <p>Category is empty.</p>
      <%= link_to 'Add Category', new_group_path, class: 'btn btn-primary' %>
    </div>
  <% else %>
    <% 1.times do %>
      <%= link_to controller: 'groups', action: 'show', id: 1 do %>
        <div class="d-flex justify-content-between align-items-center bg-white p-2 gap-6 m-2 shadow-sm">
          <div class="d-flex justify-content-start align-items-center gap-3">
            <%# <img src="<%= 'group.icon' %>
            <div class="flex-column d-flex justify-content-between mt-4">
              <%# < class="pb-3 text-black-60"><%= 'group.name.capitalize' %>
              <%# < class="text-black-50"><%= 'group.created_at.strftime("%Y-%m-%d")' %>
            </div>
          </div>
          <div class="fw-bold">$100</div>
=======

<% if @groups.empty? %>

    <div class="d-flex flex-column justify-content-center align-items-center m-5">

        <p>Category is empty.</p>
        <%= link_to 'Add Category', new_group_path, class: 'btn btn-primary' %>

     </div>
<% else %>


 <% @groups.each do |group|%>
     <%= link_to controller: 'groups', action: 'show', id: group.id do %>
          <div class="d-flex justify-content-between align-items-center bg-white p-2 gap-6 m-2 shadow-sm" >

            <div class="d-flex justify-content-start align-items-center gap-3">
              <img src="<%= group.icon %>" height="100" width="100">
              <div class="flex-column d-flex justify-content-between mt-4">
                <h6 class="pb-3 text-black-60"><%= group.name.capitalize %></h6>
                <p class="text-black-50"><%= group.created_at.strftime("%Y-%m-%d") %></p>
              </div>
            </div>
            <div class="fw-bold">$100</div>

        </div>
      <% end %>
    <% end %>
<% end %>

</div>
  <div class="position-fixed bottom-0 w-100">
    <div class="d-flex justify-content-center align-items-center bg-white p-2">


<div class="position-fixed bottom-0 w-100">
  <div class="d-flex justify-content-center align-items-center bg-white p-2">
    <%= link_to 'Add Category', new_group_path, class: 'btn btn-primary w-full w-100', style: 'background-color: #5fb523;' %>
  </div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
    <title>BudgetMate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track" => "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="mobile" class="navigation">
      <div id="burgerBtn"></div>
      <ul id="nav">
        <% if user_signed_in? %>
          <li><%= link_to "Home", "/", style: 'color: white;' %></li>
          <% @groups.each do |group| %>
            <li>
              <%= link_to group_path(group), style: 'color: white;' do %>
                <%= group.name.capitalize %>
              <% end %>
            </li>
          <% end %>
         
        <% else %>
         <li><%= link_to "Sign up", new_user_registration_path, style: 'color: white;' %></li>
         <li><%= link_to "Log in", new_user_session_path, style: 'color: white;' %></li>

        <% end %>
      </ul>
      <main id="bodyContent">
        <% if notice %>
          <p class="notice"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert"><%= alert %></p>
        <% end %>
        <%= yield %>
      </main>
    </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
</html>

app/views/shared/_navigation.html.erb
    <nav class="navbar navbar-default navbar-expand-lg fixed-top">
    <div class="container flex justify-content0-between align-items-center">

      <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDefault" aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
     
      <a class="navbar-brand text-brand" href="/">MyRecipe</a>



      <a class="navbar-brand text-brand" href="/">Next</a>

    </div>
  </nav>